### ISSUE TITLE
Maybe Workspace Behavior > General Behavior is wrong?

### ISSUE THREAD

**Issue by pintassilgo** [shalva97/kde-configuration-files#12]
Plasma has the weird default of opening files/folders by single-click. The option to change this is in `Workspace Behavior > General Behavior`.

But my `.config/plasmarc` has nothing about that. I don't know where `General Behavior` settings are actually stored and would like to know, because running Dolphin as root is still opening files/folders by single-click.

Edit: well, at least the single-click setting is in `.config/kdeglobals`.

> [KDE]
> SingleClick=false

**Comment by shalva97** [comment]
Yes, it can be wrong. I do not use Linux or KDE and have not updated the repo for a while. You could send PR about that.

The way I did it was to use Git in .config folder. Intellij IDEA has a really nice UI for it. So the flow was simple: commit -> change settings -> write changed files to README -> commit -> change another setting... and so on...

**Comment by chxei** [comment]
@pintassilgo 

> because running Dolphin as root is still opening files/folders by single-click.

That's because when launching something as root, the caller of the app is no longer same user, so home directory for that program  is not /home/youruser, rather its /root. If it can't find config there it will then look to defaults, which is /etc/skell in generall. Even if there's no config it will run as it coded to do so when no config is provided. So running something with root is an exception that we don't want to alter. Instead you should run dolphin as normal user, call it from terminal and it will promt for password if necessary

**Comment by chxei** [comment]
@shalva97 I think this one can be closed

**Comment by shalva97** [comment]
Agreed with chxei...
