### ISSUE TITLE
setting kwinscreenedges elements sans GUI

### ISSUE THREAD

**Issue by BETLOG** [shalva97/kde-configuration-files#7]
is it possible to use 
`kcmshell5 kwinscreenedges`
to set the screen corners/edges actions?
I specifically need to do this on the command line. (to set and disable minimize all when i am in a particular game, or not)

**Comment by chxei** [comment]
@BETLOG
kcmshell5 is not something usefull for scripting, but it is possible with other way: 
`kwriteconfig5 --file $HOME/.config/kwinrc --group Script-minimizeall --key BorderActivate "9"`

this will deactivate action but you need to reconfigure kde to load new config with : 
`qdbus org.kde.KWin /KWin reconfigure;`

same way you can enable action 
`kwriteconfig5 --file $HOME/.config/kwinrc --group Script-minimizeall --key BorderActivate "3"`
`qdbus org.kde.KWin /KWin reconfigure;`
here instead of 3 you can use different value of your desire. see [this](https://github.com/shalva97/kde-configuration-files#screen-edges)

**Comment by BETLOG** [comment]
Excellent. Thanks
